"""initial_schema

Revision ID: b9c7bd993bed
Revises: 
Create Date: 2026-04-18 13:39:56.789366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9c7bd993bed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('strava_gear_id', sa.Text(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_cost_cad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strava_gear_id')
    )
    op.create_table('strava_auth',
    sa.Column('id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('athlete_id', sa.BigInteger(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('id = 1', name='single_row'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trailforks_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('region', sa.Text(), server_default='nanaimo', nullable=False),
    sa.Column('difficulty', sa.Text(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=True),
    sa.Column('length_m', sa.Integer(), nullable=True),
    sa.Column('descent_m', sa.Integer(), nullable=True),
    sa.Column('ascent_m', sa.Integer(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('last_refreshed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trailforks_id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strava_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('activity_type', sa.Text(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('moving_time_s', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Numeric(), nullable=False),
    sa.Column('elevation_gain_m', sa.Numeric(), nullable=True),
    sa.Column('avg_speed_mps', sa.Numeric(), nullable=True),
    sa.Column('max_speed_mps', sa.Numeric(), nullable=True),
    sa.Column('avg_heartrate', sa.Numeric(), nullable=True),
    sa.Column('max_heartrate', sa.Numeric(), nullable=True),
    sa.Column('bike_id', sa.Integer(), nullable=True),
    sa.Column('strava_gear_id', sa.Text(), nullable=True),
    sa.Column('weather', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('raw_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bike_id'], ['bikes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strava_id')
    )
    op.create_index('idx_activities_start_time', 'activities', [sa.text('start_time DESC')], unique=False)
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bike_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('installed_at', sa.Date(), nullable=False),
    sa.Column('installed_cost_cad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('replacement_threshold_km', sa.Numeric(), nullable=True),
    sa.Column('replacement_threshold_hours', sa.Numeric(), nullable=True),
    sa.Column('replacement_threshold_days', sa.Integer(), nullable=True),
    sa.Column('current_status', sa.Text(), server_default='active', nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bike_id'], ['bikes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_trails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('trail_id', sa.Integer(), nullable=False),
    sa.Column('overlap_m', sa.Numeric(), nullable=False),
    sa.Column('overlap_pct', sa.Numeric(), nullable=False),
    sa.Column('elapsed_s', sa.Integer(), nullable=True),
    sa.Column('avg_speed_mps', sa.Numeric(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=True),
    sa.Column('matched_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trail_id'], ['trails.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'trail_id')
    )
    op.create_index('idx_activity_trails_activity', 'activity_trails', ['activity_id'], unique=False)
    op.create_index('idx_activity_trails_trail', 'activity_trails', ['trail_id'], unique=False)
    op.create_table('maintenance_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bike_id', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('cost_cad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bike_id'], ['bikes.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_log')
    op.drop_index('idx_activity_trails_trail', table_name='activity_trails')
    op.drop_index('idx_activity_trails_activity', table_name='activity_trails')
    op.drop_table('activity_trails')
    op.drop_table('components')
    op.drop_index('idx_activities_start_time', table_name='activities')
    op.drop_table('activities')
    op.drop_table('trails')
    op.drop_table('strava_auth')
    op.drop_table('bikes')
    # ### end Alembic commands ###
